# Complete database export
# Generated automatically

import base64


# VENDORS (8 rows)
vendors_data = [
    {
        'vendor_id': '5000000015',
        'title': '0002',
        'first_name': 'John A',
        'last_name': 'DREIER',
        'email': 'susanfrogers@gmail.com',
        'password_hash': '$2b$12$kdGQQ35qWZnH8GPvHygOyuXY4gSrn0y/I5MI.s55fzumxYUIot7CC',
        'mobile': '07700 111 222',
        'telephone': '020 7946 1234',
        'created_at': '2025-12-11T22:21:21.793398',
        'updated_at': '2025-12-12T04:56:15.325945',
    },
    {
        'vendor_id': '5000000061',
        'title': 'Mr.',
        'first_name': 'D',
        'last_name': 'L BOLTON',
        'email': 'farm@boltonfarms.co.uk',
        'password_hash': '$2b$12$kdGQQ35qWZnH8GPvHygOyuXY4gSrn0y/I5MI.s55fzumxYUIot7CC',
        'mobile': '07822 333 444',
        'telephone': '020 7946 5678',
        'created_at': '2025-12-11T22:21:19.580554',
        'updated_at': '2025-12-12T05:29:50.474288',
    },
    {
        'vendor_id': '5000000078',
        'title': 'Mr',
        'first_name': 'Beam',
        'email': 'beam@ukpn.co.com',
        'created_at': '2025-12-16T07:48:28.368474',
        'updated_at': '2025-12-16T07:48:28.368474',
    },
    {
        'vendor_id': '5000000068',
        'title': '',
        'first_name': 'AQUELINE',
        'last_name': 'JANET',
        'email': 'janet@ukpn.co.com',
        'created_at': '2025-12-16T08:06:25.145499',
        'updated_at': '2025-12-16T08:06:25.145499',
    },
    {
        'vendor_id': '5000000685',
        'title': 'Mrs',
        'first_name': 'J L',
        'last_name': 'PEARCE',
        'email': 'pearce@ukpn.co.com',
        'created_at': '2025-12-16T08:08:16.572511',
        'updated_at': '2025-12-16T08:08:16.572511',
    },
    {
        'vendor_id': '5000000054',
        'title': 'MR',
        'first_name': 'G J',
        'last_name': 'GEORGE',
        'email': 'george@ukpn.co.com',
        'created_at': '2025-12-16T08:37:07.505795',
        'updated_at': '2025-12-16T08:37:07.505795',
    },
    {
        'vendor_id': '5000000058',
        'title': '',
        'first_name': 'B M',
        'last_name': 'CLENSHAW',
        'email': 'clenshaw@ukpn.co.com',
        'created_at': '2025-12-16T08:38:27.416423',
        'updated_at': '2025-12-16T08:38:27.416423',
    },
    {
        'vendor_id': '5000003289',
        'title': 'MR',
        'first_name': 'A D',
        'last_name': 'POOLE',
        'email': 'poole@ukpn.co.com',
        'created_at': '2025-12-16T08:45:15.866656',
        'updated_at': '2025-12-16T08:45:15.866656',
    },
]

# USER_DETAILS (2 rows)
user_details_data = [
    {
        'id': 28,
        'vendor_id': '5000000015',
        'street': 'TAMLEY COTTAGE',
        'address_line1': 'TAMLEY LANE',
        'address_line2': 'HASTINGLEIGH',
        'city': 'ASHFORD',
        'postcode': 'TN25 5HW',
        'created_at': '2025-12-11T22:21:21.796316',
        'updated_at': '2025-12-12T10:15:58.999667',
        'user_agreement_url': '/documents/user_agreements/user_agreement_5000000015_20251212_101558.pdf',
    },
    {
        'id': 27,
        'vendor_id': '5000000061',
        'street': 'BORHEAM HALL',
        'address_line1': 'THE CHASE',
        'address_line2': 'BOREHAM',
        'city': 'CHELMSFORD',
        'postcode': 'CM3 3DQ',
        'created_at': '2025-12-11T22:21:19.583462',
        'updated_at': '2025-12-16T13:27:19.483615',
        'user_agreement_url': '/documents/user_agreements/user_agreement_5000000061_20251216_132719.pdf',
    },
]

# BANK_DETAILS (2 rows)
bank_details_data = [
    {
        'id': 13,
        'vendor_id': '5000000061',
        'account_number': '98765432',
        'sort_code': '50-60-70',
        'account_holder_name': 'D L BOLTON',
        'payment_method': 'BACS',
        'zahls': '-',
        'confs': '-',
        'sperr': '-',
        'created_at': '2025-12-01T10:00:00',
        'updated_at': '2025-12-12T05:55:00.229982',
    },
    {
        'id': 14,
        'vendor_id': '5000000015',
        'account_number': '22222222',
        'sort_code': '20-30-40',
        'account_holder_name': 'John A DREIER UPDATED',
        'payment_method': 'K',
        'zahls': '-',
        'confs': '-',
        'sperr': '-',
        'created_at': '2025-12-01T10:00:00',
        'updated_at': '2025-12-12T05:55:00.229982',
    },
]

# PAYMENT_HISTORY (3 rows)
payment_history_data = [
    {
        'id': 8,
        'vendor_id': '5000000061',
        'company_code': '1700',
        'fiscal_year': '2023',
        'clearing_doc': '2000026151',
        'document_number': '5110702087',
        'reference_doc': '5110702087',
        'gross_amount': '268.40',
        'net_amount': '268.40',
        'tax_amount': '0.00',
        'tax_code': 'V0',
        'tax_text': 'Exempt from input VAT',
        'purchase_order': '1000000121',
        'document_type': 'ZWLA',
        'posting_date': '2023-11-07',
        'document_date': '2023-11-07',
        'doc_type': 'YW',
        'rental_amount': '207.76',
        'compensation_amount': '325.50',
        'lease_amount': '0.00',
        'cheque_number': '257577',
        'payment_date': '2023-11-08',
        'payment_method': 'K',
        'payment_amount': '268.40',
        'encashment_date': '2023-11-21',
        'created_at': '2025-12-11T22:21:19.588859',
    },
    {
        'id': 9,
        'vendor_id': '5000000061',
        'company_code': '1700',
        'fiscal_year': '2024',
        'clearing_doc': '2000005034',
        'document_number': '5110846809',
        'reference_doc': '5110846809',
        'gross_amount': '264.86',
        'net_amount': '264.86',
        'tax_amount': '0.00',
        'tax_code': 'V0',
        'tax_text': 'Exempt from input VAT',
        'purchase_order': '1000000121',
        'document_type': 'ZWLA',
        'posting_date': '2024-03-26',
        'document_date': '2024-03-26',
        'doc_type': 'YW',
        'rental_amount': '103.88',
        'compensation_amount': '160.98',
        'lease_amount': '0.00',
        'cheque_number': '268615',
        'payment_date': '2024-03-27',
        'payment_method': 'K',
        'payment_amount': '264.86',
        'encashment_date': '2024-04-12',
        'created_at': '2025-12-11T22:21:19.592110',
    },
    {
        'id': 10,
        'vendor_id': '5000000015',
        'company_code': '1900',
        'fiscal_year': '2023',
        'clearing_doc': '2000017143',
        'document_number': '5110697500',
        'reference_doc': '5110697500',
        'gross_amount': '888.00',
        'net_amount': '888.00',
        'tax_amount': '0.00',
        'tax_code': 'V0',
        'tax_text': 'Exempt from input VAT',
        'purchase_order': '1000000003',
        'document_type': 'ZWLT',
        'posting_date': '2023-11-01',
        'document_date': '2023-11-01',
        'doc_type': 'YW',
        'rental_amount': '0.00',
        'compensation_amount': '2280.00',
        'lease_amount': '0.00',
        'cheque_number': '171572',
        'payment_date': '2023-11-02',
        'payment_method': 'K',
        'payment_amount': '888.00',
        'encashment_date': '2023-11-09',
        'void_reason': '00',
        'void_text': '',
        'created_at': '2025-12-11T22:21:21.802355',
    },
]

# PAYMENT_SCHEDULE_HEADERS (2 rows)
payment_schedule_headers_data = [
    {
        'id': 3,
        'vendor_id': '5000000061',
        'agreement_number': '1000000121',
        'agreement_type': 'ZWLA',
        'location': 'LAND LYING',
        'last_payment_date': '2024-03-20',
        'next_payment_date': '2025-03-20',
        'total_consent': '264.86',
        'currency': 'GBP',
        'created_at': '2025-12-11T22:21:19.593550',
        'updated_at': '2025-12-11T22:21:19.593550',
    },
    {
        'id': 4,
        'vendor_id': '5000000015',
        'agreement_number': '1000000003',
        'agreement_type': 'ZWLT',
        'location': '',
        'last_payment_date': '2023-11-01',
        'total_consent': '0.00',
        'currency': '',
        'created_at': '2025-12-11T22:21:21.805724',
        'updated_at': '2025-12-11T22:21:21.805724',
    },
]

# PAYMENT_SCHEDULE_ITEMS (7 rows)
payment_schedule_items_data = [
    {
        'id': 8,
        'agreement_number': '1000000121',
        'item_number': '00010',
        'agreement_type': 'ZWLA',
        'start_date': '2022-03-21',
        'location': 'LAND LYING',
        'land_reg_number': 'EX345302',
        'functional_location': '016',
        'asset_type': 'Pole/Tower',
        'asset_number': '016',
        'short_text': 'ARABLE TOWER SYSTEM- BROAD BASE',
        'last_payment_date': '2024-03-20',
        'next_payment_date': '2025-03-20',
        'multiplier': '1.000',
        'rental': '51.94',
        'compensation': '80.49',
        'lease_amount': '0.00',
        'currency': 'GBP',
        'created_at': '2025-12-11T22:21:19.596743',
        'updated_at': '2025-12-11T22:21:19.596743',
    },
    {
        'id': 9,
        'agreement_number': '1000000121',
        'item_number': '00020',
        'agreement_type': 'ZWLA',
        'start_date': '2022-03-21',
        'location': 'LAND LYING',
        'land_reg_number': 'EX345302',
        'functional_location': '017',
        'asset_type': 'Pole/Tower',
        'asset_number': '017',
        'short_text': 'ARABLE TOWER SYSTEM- BROAD BASE',
        'last_payment_date': '2024-03-20',
        'next_payment_date': '2025-03-20',
        'multiplier': '1.000',
        'rental': '51.94',
        'compensation': '80.49',
        'lease_amount': '0.00',
        'currency': 'GBP',
        'created_at': '2025-12-11T22:21:19.596743',
        'updated_at': '2025-12-11T22:21:19.596743',
    },
    {
        'id': 10,
        'agreement_number': '1000000003',
        'item_number': '00010',
        'agreement_type': 'ZWLT',
        'start_date': '2021-10-20',
        'location': '',
        'land_reg_number': 'K651089',
        'functional_location': '',
        'asset_type': '',
        'asset_number': '',
        'short_text': 'ARABLE SINGLE POLE WITH 1 STAY 884095',
        'last_payment_date': '2023-11-01',
        'multiplier': '1.000',
        'rental': '0.00',
        'compensation': '0.00',
        'lease_amount': '0.00',
        'currency': '',
        'created_at': '2025-12-11T22:21:21.808826',
        'updated_at': '2025-12-11T22:21:21.808826',
    },
    {
        'id': 11,
        'agreement_number': '1000000003',
        'item_number': '00020',
        'agreement_type': 'ZWLT',
        'start_date': '2021-10-20',
        'location': '',
        'land_reg_number': 'K758844',
        'functional_location': '',
        'asset_type': '',
        'asset_number': '',
        'short_text': 'HEDGEROW SINGLE POLE 884094',
        'last_payment_date': '2023-11-01',
        'multiplier': '1.000',
        'rental': '0.00',
        'compensation': '0.00',
        'lease_amount': '0.00',
        'currency': '',
        'created_at': '2025-12-11T22:21:21.808826',
        'updated_at': '2025-12-11T22:21:21.808826',
    },
    {
        'id': 12,
        'agreement_number': '1000000003',
        'item_number': '00030',
        'agreement_type': 'ZWLT',
        'start_date': '2021-10-20',
        'location': '',
        'land_reg_number': 'K758844',
        'functional_location': '',
        'asset_type': '',
        'asset_number': '',
        'short_text': 'HEDGEROW SINGLE POLE 884062',
        'last_payment_date': '2023-11-01',
        'multiplier': '1.000',
        'rental': '0.00',
        'compensation': '0.00',
        'lease_amount': '0.00',
        'currency': '',
        'created_at': '2025-12-11T22:21:21.808826',
        'updated_at': '2025-12-11T22:21:21.808826',
    },
    {
        'id': 13,
        'agreement_number': '1000000003',
        'item_number': '00040',
        'agreement_type': 'ZWLT',
        'start_date': '2021-10-20',
        'location': '',
        'land_reg_number': 'K768575',
        'functional_location': '',
        'asset_type': '',
        'asset_number': '',
        'short_text': 'HEDGEROW SINGLE POLE 884086',
        'last_payment_date': '2023-11-01',
        'multiplier': '1.000',
        'rental': '0.00',
        'compensation': '0.00',
        'lease_amount': '0.00',
        'currency': '',
        'created_at': '2025-12-11T22:21:21.808826',
        'updated_at': '2025-12-11T22:21:21.808826',
    },
    {
        'id': 14,
        'agreement_number': '1000000003',
        'item_number': '00050',
        'agreement_type': 'ZWLT',
        'start_date': '2021-10-20',
        'location': '',
        'land_reg_number': 'K758844',
        'functional_location': '',
        'asset_type': '',
        'asset_number': '',
        'short_text': 'HEDGEROW SINGLE POLE WITH 1 STAY 884085',
        'last_payment_date': '2023-11-01',
        'multiplier': '1.000',
        'rental': '0.00',
        'compensation': '0.00',
        'lease_amount': '0.00',
        'currency': '',
        'created_at': '2025-12-11T22:21:21.808826',
        'updated_at': '2025-12-11T22:21:21.808826',
    },
]

# REMITTANCE_DOCUMENTS (3 rows)
remittance_documents_data = [
    {
        'id': 9,
        'vendor_id': '5000000061',
        'fiscal_year': '2024',
        'file_name': '5000000061_2025-12-10T10_32_28.4654212Z.pdf',
        'file_data': '<memory at 0x7667d4783d00>',
        'mime_type': 'application/pdf',
        'file_size': 235329,
        'created_at': '2025-12-15T12:43:39.218338',
        'updated_at': '2025-12-15T12:43:39.217340',
    },
    {
        'id': 10,
        'vendor_id': '5000000061',
        'fiscal_year': '2023',
        'file_name': '5000000061_2023.pdf',
        'file_data': '<memory at 0x7667d46b8040>',
        'mime_type': 'application/pdf',
        'file_size': 172941,
        'created_at': '2025-12-15T12:43:56.133822',
        'updated_at': '2025-12-15T12:43:56.132996',
    },
    {
        'id': 11,
        'vendor_id': '5000000015',
        'fiscal_year': '2023',
        'file_name': 'Remittance_Schedule_2023_5000000015.pdf',
        'file_data': '<memory at 0x7667d46b8100>',
        'mime_type': 'application/pdf',
        'file_size': 238503,
        'created_at': '2025-12-15T12:44:48.549170',
        'updated_at': '2025-12-15T12:44:48.548607',
    },
]

# REMITTANCE_REPORTS (7 rows)
remittance_reports_data = [
    {
        'id': 10,
        'fiscal_year': 2023,
        'document_name': '5000000015.pdf',
        'document_url': '/documents/remittance/2023/2023_20251211_212239.pdf',
        'document_type': 'PDF',
        'created_at': '2025-12-11T21:22:39.614534',
        'updated_at': '2025-12-11T21:22:39.614534',
        'postcode': 'TN255HW',
        'vendor_id': '5000000015',
    },
    {
        'id': 11,
        'fiscal_year': 2023,
        'document_name': '5000000061.pdf',
        'document_url': '/documents/remittance/2023/2023_20251211_212723.pdf',
        'document_type': 'PDF',
        'created_at': '2025-12-11T21:27:23.105464',
        'updated_at': '2025-12-11T21:27:23.105464',
        'postcode': 'CM33DQ',
        'vendor_id': '5000000061',
    },
    {
        'id': 13,
        'fiscal_year': 2024,
        'document_name': '5000000061.pdf',
        'document_url': '/documents/remittance/2024/2024_20251211_212901.pdf',
        'document_type': 'PDF',
        'created_at': '2025-12-11T21:29:01.557993',
        'updated_at': '2025-12-11T21:29:01.557993',
        'postcode': 'CM33DQ',
        'vendor_id': '5000000061',
    },
    {
        'id': 12,
        'fiscal_year': 2024,
        'document_name': '5000003289.pdf',
        'document_url': '/documents/remittance/2024/2024_20251211_212831.pdf',
        'document_type': 'PDF',
        'created_at': '2025-12-11T21:28:31.510559',
        'updated_at': '2025-12-11T21:28:31.510559',
        'postcode': 'TN126HT',
        'vendor_id': '5000003289',
    },
    {
        'id': 19,
        'fiscal_year': 2022,
        'document_name': 'CM3 3DQ.pdf.pdf',
        'document_url': '/documents/remittance/2022/2022_20251216_085529.pdf',
        'document_type': 'PDF',
        'created_at': '2025-12-16T08:55:29.899676',
        'updated_at': '2025-12-16T08:55:29.899676',
        'postcode': 'CM33DQ',
        'vendor_id': '5000000685',
    },
    {
        'id': 18,
        'fiscal_year': 2022,
        'document_name': 'TN25 5HW_1.pdf.pdf',
        'document_url': '/documents/remittance/2022/2022_20251216_085450.pdf',
        'document_type': 'PDF',
        'created_at': '2025-12-16T08:54:50.435222',
        'updated_at': '2025-12-16T08:54:50.435222',
        'postcode': 'TN255HW',
        'vendor_id': '5000000068',
    },
    {
        'id': 17,
        'fiscal_year': 2022,
        'document_name': 'TN25 5HW.pdf.pdf',
        'document_url': '/documents/remittance/2022/2022_20251216_085417.pdf',
        'document_type': 'PDF',
        'created_at': '2025-12-16T08:54:17.769963',
        'updated_at': '2025-12-16T08:54:17.769963',
        'postcode': 'TN255HW',
        'vendor_id': '5000000078',
    },
]

# GEOGRAPHICAL_DOCUMENTS (7 rows)
geographical_documents_data = [
    {
        'id': 19,
        'postcode': 'CM33DQ',
        'document_name': '5000000061.pdf',
        'document_url': '/documents/geographical/CM33DQ_20251211_213430.pdf',
        'document_type': 'PDF',
        'latitude': '51.75184320',
        'longitude': '0.53884900',
        'created_at': '2025-12-11T21:34:30.865003',
        'updated_at': '2025-12-11T21:34:30.865003',
        'vendor_id': '5000000061',
    },
    {
        'id': 20,
        'postcode': 'TN126HT',
        'document_name': '5000000058.pdf',
        'document_url': '/documents/geographical/TN126HT_20251211_213502.pdf',
        'document_type': 'PDF',
        'latitude': '51.17817280',
        'longitude': '0.39179870',
        'created_at': '2025-12-11T21:35:03.032489',
        'updated_at': '2025-12-11T21:35:03.032489',
        'vendor_id': '5000000058',
    },
    {
        'id': 21,
        'postcode': 'RH158NB',
        'document_name': '5000000054.pdf',
        'document_url': '/documents/geographical/RH158NB_20251211_213526.pdf',
        'document_type': 'PDF',
        'latitude': '50.96287300',
        'longitude': '-0.13869130',
        'created_at': '2025-12-11T21:35:26.845565',
        'updated_at': '2025-12-11T21:35:26.845565',
        'vendor_id': '5000000054',
    },
    {
        'id': 22,
        'postcode': 'TN255HW',
        'document_name': '5000000015.pdf',
        'document_url': '/documents/geographical/TN255HW_20251211_213550.pdf',
        'document_type': 'PDF',
        'latitude': '51.16310380',
        'longitude': '0.99620720',
        'created_at': '2025-12-11T21:35:50.703388',
        'updated_at': '2025-12-11T21:35:50.703388',
        'vendor_id': '5000000015',
    },
    {
        'id': 23,
        'postcode': 'TN255HW',
        'document_name': 'TN25 5HW.pdf.pdf',
        'document_url': '/documents/geographical/TN255HW_20251216_062855.pdf',
        'document_type': 'PDF',
        'latitude': '51.16310380',
        'longitude': '0.99620720',
        'created_at': '2025-12-16T06:28:57.787046',
        'updated_at': '2025-12-16T06:28:57.787046',
        'vendor_id': '5000000078',
    },
    {
        'id': 24,
        'postcode': 'TN255HW',
        'document_name': 'TN25 5HW_1.pdf.pdf',
        'document_url': '/documents/geographical/TN255HW_20251216_063015.pdf',
        'document_type': 'PDF',
        'latitude': '51.16310380',
        'longitude': '0.99620720',
        'created_at': '2025-12-16T06:30:15.992427',
        'updated_at': '2025-12-16T06:30:15.992427',
        'vendor_id': '5000000068',
    },
    {
        'id': 25,
        'postcode': 'CM33DQ',
        'document_name': 'CM3 3DQ.pdf.pdf',
        'document_url': '/documents/geographical/CM33DQ_20251216_063107.pdf',
        'document_type': 'PDF',
        'latitude': '51.75184320',
        'longitude': '0.53884900',
        'created_at': '2025-12-16T06:31:08.552987',
        'updated_at': '2025-12-16T06:31:08.552987',
        'vendor_id': '5000000685',
    },
]

# WAYLEAVE_AGREEMENTS (1 rows)
wayleave_agreements_data = [
    {
        'id': 4,
        'filename': 'User Agreement -61_up.pdf',
        'grantor_name': 'D L Bolton',
        'grantor_address': 'of Borheam Hall, The Chase, Borheam, Chelmsford',
        'grantor_telephone': '02079469678',
        'grantor_email': 'farm@bottonfarms.co.uk',
        'agreement_date': '24 day of Feb 2018',
        'agreement_ref': '5443c',
        'payment': '£150.00',
        'duration': '15 years',
        'property_location': 'Borheam Hall',
        'works_description': 'overhead electric line consisting of two',
        'drawing_number': '',
        'extracted_text': '=== TEXT CONTENT (3 pages) ===\n--- Page 1 ---\n```\nNo. 20024547\nOWNER/OCCUPIER\n(delete as appropriate)\n\nRef: 5443c\nTL4366-4653\nTel: 02079469678, E-mail: farm@bottonfarms.co.uk\n\n## Wayleave Agreement\n\nmade the 24 day of Feb 2018\n\nBETWEEN D L Bolton ("the Grantee") of Borheam Hall, The Chase, Borheam, Chelmsford, CM3 3DQ of the one part and\n\nEastern Power Networks plc whose registered office is Newington House, 237 Southwark Bridge Road, London, SE1 6NP ("the Company") of the other part.\n\nIT IS AGREED as follows:-\n\n### 1. DEFINITIONS\n\n"the Company" includes its Subsidiaries, Associated Companies, successors and assigns\n\n"the Grantee" includes its tenants, licensees and employees\n\n"the Plan" means the plan annexed hereto\n\n"the Property" means the land shown on the Plan and situated at Borheam Hall\n\n"the Works" means the works shown on the Plan and described in the Schedule\n\n### 2. THE RIGHTS\n\nTHE Grantee hereby grants consent for the Company:-\n\n(a) To install, maintain, inspect, alter, renew, remove and retain the Works and to enter the Property at all reasonable times (or at any time in the case of emergency) with or without vehicles plant or machinery for such purposes\n\n(b) To fell or lop in a woodman like manner any tree or hedge on the Property which obstructs or interferes with the Works\n\n### 3. THE COMPANY\'S COVENANTS\n\nTHE Company shall:-\n\n(a) Not cause any unnecessary damage or injury to the Property and shall take all reasonable precautions to avoid obstruction or interference with the use of any road or footpath sewer drain or watercourse that may be crossed by the Works\n\n(b) Make good to the reasonable satisfaction of the Grantee any damage caused by or arising out of the execution of the Works. If for any reason, any such damage cannot be made good the Company shall compensate the Grantee in an amount which has previously been approved by the Company\n\n(c) Give to the Grantee not less than three days\' previous notice (except in cases of emergency when as long notice as practicable shall be given) of the intended exercise of any of the rights conferred by Clause 2 above\n\n(d) On the completion of this Agreement pay the Grantee a total one-off payment of £150.00\n\n(e) At all times keep the Grantee indemnified against all losses, damages and expenses reasonably foreseeable at the date of this Agreement which he suffers or incurs, by reason or on account of any breach of this Agreement including any registrant act or omission of the Company in connection with the execution or existence of the Works provided that this indemnity shall not extend to any such losses damages or expenses to the extent caused by the default of the Grantee\n```\n\n--- Page 2 ---\n# 4. THE GRANTOR\'S COVENANTS\n\nTHE Grantor shall not:\n\n(a) Do or cause or permit to be done on the Property anything likely to cause damage or interference of any kind to the Works\n\n(b) Make or cause or permit to be made any material alteration to the Property so as to interfere with or obstruct the access to the Works or so as to interfere with the support afforded to the Works by the surrounding soil without the prior written consent of the Company\n\n# 5. TERMINATION\n\nThis Agreement shall remain in force for a period of 15 years from the date hereof and thereafter until determined at the expiry of not less than twelve months\' previous written notice given at any time by either party but without prejudice to the rights which the Company might exercise under the Electricity Act 1989\n\n# THE SCHEDULE\n\n(a) THE placing of an overhead electric line consisting of two, three or four conductors together with any ancillary apparatus across the Property in the line indicated in the approximate position shown on the Plan\n\n(13) THE erection of x anc. appliances for the purpose of supporting the a.l.t.n.e.Rtentloose electric line in the approximate positions indicated on the Plan i.e. a rect circle (red) or T (sky)\n\n(c) THE placing of x underground Lead3Lea(a) for Transmitting electricity at a frequency of SO.herds and at a pressure of 1000 volts anc. low voltage telephone anc. signalling cables such cables(a) to 13m in the approximate position indicated i.e. 13m a rect 13m line on the Plan\n\nTHE parties hereto have set their hands the day and year first above written\n\nSIGNED BY\n\n(Grantor\'s Signature) __________________________\n\n(please also sign plan)\n\nSIGNED BY\n\n(Agent\'s Signature) __________________________\n\nFor and on behalf of Eastern Power Networks plc\nTel: 03301 991841\nEmail: eastham.connections@ukpowernetworks.co.uk\n\n--- Page 3 ---\n```\nWAYLEAVE\n\nBarbara Poxton\n\nOverhead Line   EHV   c.1980CJ   Pro\nOverhead Line   HV    - - - - - -\nOverhead Line   LV    - - - - - -\nUnderground Cable EHV   - - - - - -\nUnderground Cable LV    - - - - - -\nH-Pole(s)       O-O    - - - - - -\nPole(s)         - - - - - -\nStayte(s)       r--    r--    - - - - -\nSubstation      - - - - - -\nTower/Pylon     - - - - - -\n\nSite: 5 Lower Street, Thrplow, Combs, SG8 7RJ\nDrawing No.: 5443c   TQ Number: TQ 64731\nPlotted On: 17/01/2018   Map Centre: TL 4366 4653\nScale: 1:400   Drawn by: Kristina Green\n\nStained concrete conductor may be fixed from any pole. This is not a precise drawing and is for guidance only. The exact position of the overhead line network (Operated by UK Power Networks) before any excavation is omitted in the drawing. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead line network. The drawing is not to be used for any purpose other than to indicate the approximate position of the overhead',
        'created_at': '2025-12-16T17:34:08.817289+00:00',
        'updated_at': '2025-12-16T17:34:08.817289+00:00',
        'grantor_postcode': 'CM3 3DQ',
        'tq_number': 'TQ64731',
        'company_with': 'Eastern Power Networks plc whose registered office is Newington House, 237 Southwark Bridge Road, London, SE1 6NP',
    },
]

# MOVING_HOUSE_NOTIFICATIONS (2 rows)
moving_house_notifications_data = [
    {
        'id': 17,
        'vendor_id': '5000000015',
        'old_address': 'TAMLEY COTTAGE, TAMLEY LANE, HASTINGLEIGH',
        'old_postcode': 'TN25 5HW',
        'new_address': '15 PARK AVENUE, ASHFORD',
        'new_postcode': 'TN24 8EX',
        'new_owner_name': 'Robert Smith',
        'new_owner_email': 'r.smith@example.com',
        'new_owner_mobile': '07700 123 456',
        'submission_date': '2025-12-11T18:22:08.014766',
        'status': 'pending',
        'created_at': '2025-12-11T22:22:08.014774',
        'updated_at': '2025-12-11T22:22:08.014774',
    },
    {
        'id': 18,
        'vendor_id': '5000000061',
        'old_address': 'BORHEAM HALL, THE CHASE, BOREHAM',
        'old_postcode': 'CM3 3DQ',
        'new_address': '25 HIGH STREET, CHELMSFORD',
        'new_postcode': 'CM1 1BE',
        'new_owner_name': 'Emma Johnson',
        'new_owner_email': 'e.johnson@example.com',
        'new_owner_mobile': '07900 654 321',
        'submission_date': '2025-12-10T10:23:09.789246',
        'status': 'pending',
        'created_at': '2025-12-11T22:23:09.789251',
        'updated_at': '2025-12-11T22:23:09.789251',
    },
]

# BANK_DETAILS_AUDIT (0 rows)
bank_details_audit_data = [
]

# VENDOR_AUDIT (0 rows)
vendor_audit_data = [
]
