"""Initial migration with all tables

Revision ID: 95b6c1509bb5
Revises: 
Create Date: 2025-12-16 17:38:21.977930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95b6c1509bb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bank_audit_changed_at'), table_name='bank_details_audit')
    op.drop_index(op.f('idx_bank_audit_vendor_id'), table_name='bank_details_audit')
    op.drop_table('bank_details_audit')
    op.drop_index(op.f('idx_moving_house_status'), table_name='moving_house_notifications')
    op.drop_index(op.f('idx_moving_house_vendor'), table_name='moving_house_notifications')
    op.drop_table('moving_house_notifications')
    op.drop_index(op.f('idx_vendor_audit_changed_at'), table_name='vendor_audit')
    op.drop_index(op.f('idx_vendor_audit_vendor_id'), table_name='vendor_audit')
    op.drop_table('vendor_audit')
    op.drop_index(op.f('idx_geographical_postcode'), table_name='geographical_documents')
    op.drop_index(op.f('idx_geographical_vendor_id'), table_name='geographical_documents')
    op.drop_table('geographical_documents')
    op.drop_index(op.f('idx_remittance_vendor_id'), table_name='remittance_reports')
    op.drop_table('remittance_reports')
    op.alter_column('bank_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bank_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('payment_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_payment_history_date'), table_name='payment_history')
    op.drop_index(op.f('idx_payment_history_vendor'), table_name='payment_history')
    op.alter_column('payment_schedule_headers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('payment_schedule_headers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_payment_schedule_vendor'), table_name='payment_schedule_headers')
    op.alter_column('payment_schedule_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('payment_schedule_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_payment_schedule_items_agreement'), table_name='payment_schedule_items')
    op.alter_column('remittance_documents', 'file_data',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('remittance_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('remittance_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_remittance_fiscal_year'), table_name='remittance_documents')
    op.drop_index(op.f('idx_remittance_vendor'), table_name='remittance_documents')
    op.drop_index(op.f('idx_remittance_vendor_year'), table_name='remittance_documents')
    op.alter_column('user_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('user_details', 'user_agreement_url')
    op.alter_column('vendors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vendors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_vendors_email'), table_name='vendors')
    op.alter_column('wayleave_agreements', 'grantor_postcode',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Postcode extracted separately from grantor address',
               existing_nullable=True)
    op.alter_column('wayleave_agreements', 'tq_number',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='TQ number extracted from wayleave agreement document',
               existing_nullable=True)
    op.drop_index(op.f('idx_wayleave_created_at'), table_name='wayleave_agreements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_wayleave_created_at'), 'wayleave_agreements', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('wayleave_agreements', 'tq_number',
               existing_type=sa.VARCHAR(length=100),
               comment='TQ number extracted from wayleave agreement document',
               existing_nullable=True)
    op.alter_column('wayleave_agreements', 'grantor_postcode',
               existing_type=sa.VARCHAR(length=20),
               comment='Postcode extracted separately from grantor address',
               existing_nullable=True)
    op.create_index(op.f('idx_vendors_email'), 'vendors', ['email'], unique=False)
    op.alter_column('vendors', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('vendors', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('user_details', sa.Column('user_agreement_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('user_details', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_details', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('idx_remittance_vendor_year'), 'remittance_documents', ['vendor_id', 'fiscal_year'], unique=False)
    op.create_index(op.f('idx_remittance_vendor'), 'remittance_documents', ['vendor_id'], unique=False)
    op.create_index(op.f('idx_remittance_fiscal_year'), 'remittance_documents', ['fiscal_year'], unique=False)
    op.alter_column('remittance_documents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('remittance_documents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('remittance_documents', 'file_data',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    op.create_index(op.f('idx_payment_schedule_items_agreement'), 'payment_schedule_items', ['agreement_number'], unique=False)
    op.alter_column('payment_schedule_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('payment_schedule_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('idx_payment_schedule_vendor'), 'payment_schedule_headers', ['vendor_id'], unique=False)
    op.alter_column('payment_schedule_headers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('payment_schedule_headers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('idx_payment_history_vendor'), 'payment_history', ['vendor_id'], unique=False)
    op.create_index(op.f('idx_payment_history_date'), 'payment_history', ['posting_date'], unique=False)
    op.alter_column('payment_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bank_details', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bank_details', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('remittance_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fiscal_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=50), server_default=sa.text("'PDF'::character varying"), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('remittance_reports_pkey')),
    comment='Stores remittance reports organized by fiscal year'
    )
    op.create_index(op.f('idx_remittance_vendor_id'), 'remittance_reports', ['vendor_id'], unique=False)
    op.create_table('geographical_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('postcode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('document_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=50), server_default=sa.text("'PDF'::character varying"), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('geographical_documents_pkey')),
    comment='Stores documents linked to geographical locations (postcodes)'
    )
    op.create_index(op.f('idx_geographical_vendor_id'), 'geographical_documents', ['vendor_id'], unique=False)
    op.create_index(op.f('idx_geographical_postcode'), 'geographical_documents', ['postcode'], unique=False)
    op.create_table('vendor_audit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('change_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vendor_audit_pkey'))
    )
    op.create_index(op.f('idx_vendor_audit_vendor_id'), 'vendor_audit', ['vendor_id'], unique=False)
    op.create_index(op.f('idx_vendor_audit_changed_at'), 'vendor_audit', ['changed_at'], unique=False)
    op.create_table('moving_house_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('old_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('old_postcode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('new_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('new_postcode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('new_owner_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('new_owner_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('new_owner_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('submission_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], name=op.f('moving_house_notifications_vendor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('moving_house_notifications_pkey'))
    )
    op.create_index(op.f('idx_moving_house_vendor'), 'moving_house_notifications', ['vendor_id'], unique=False)
    op.create_index(op.f('idx_moving_house_status'), 'moving_house_notifications', ['status'], unique=False)
    op.create_table('bank_details_audit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bank_details_audit_pkey'))
    )
    op.create_index(op.f('idx_bank_audit_vendor_id'), 'bank_details_audit', ['vendor_id'], unique=False)
    op.create_index(op.f('idx_bank_audit_changed_at'), 'bank_details_audit', ['changed_at'], unique=False)
    # ### end Alembic commands ###
